version: "3.9"
services:
  db:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=techtest
    ports:
      - "13306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  seeder:
    build: ./seeder
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "node dist/index.js"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: secret
      NODE_ENV: development
      WAIT_HOSTS: db:3306
